Repository marcolivierarsenault/moonraker-home-assistant, pull requests merged in 2023-03, with the labels that each got.

#21 Sensor: use icons that better match a 3D-printer
  custom_components/moonraker/sensor.py
Labels: enhancement

#26 update GH issue template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
Labels: documentation

#20 Add a menu entry to change the moonraker port when configuring the in…
  custom_components/moonraker/__init__.py
  custom_components/moonraker/api.py
  custom_components/moonraker/config_flow.py
  custom_components/moonraker/const.py
  custom_components/moonraker/translations/en.json
  tests/const.py
  tests/test_api.py
  tests/test_config_flow.py
Labels: enhancement

#36 add control over failing thumbnail
  custom_components/moonraker/__init__.py
  tests/test_camera.py
Labels: bug

#44 add empty string on Null display message
  custom_components/moonraker/sensor.py
Labels: bug

#64 fix_duplicate_temp_sensor
  custom_components/moonraker/sensor.py
  tests/test_sensor.py
Labels: bug

#65 manage optional sensor key conflict
  custom_components/moonraker/sensor.py
  tests/test_sensor.py
Labels: bug

#67 change entry setup to async
  custom_components/moonraker/__init__.py
Labels: bug

#70 update Readmes
  README.md
  assets/button.png
  assets/thumbnail.png
  info.md
Labels: documentation

#81 move fan to optional sensor
  custom_components/moonraker/sensor.py
  tests/test_sensor.py
Labels: bug
